app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::filter('auth', function()
{
    if ( Auth::guest() ) // If the user is not logged in
    {
        return Redirect::guest('user/login');
    }
});

// Only authenticated users will be able to access routes that begins with
// 'admin'. Ex: 'admin/posts', 'admin/categories'.
Route::when('admin*', 'auth'); 

Route::get('/', 'HomeController@showWelcome');

Route::get('admin', array('as' => 'admin..dashboard.index', 'uses' => 'admin\DashboardController@index'));

Route::resource('/pages', 'PagesController');

Route::get('/posts/tags/{tags}', array('as' => 'post.index.tag', 'uses' => 'PostsController@index_tag'));
Route::get('/posts/category/{id}', array('as' => 'post.index.category', 'uses' => 'PostsController@index_category'));
Route::resource('/posts', 'PostsController');

Route::get('/products/tags/{tags}', array('as' => 'products.index.tag', 'uses' => 'ProductsController@index_tag'));
Route::get('/products/category/{id}', array('as' => 'products.index.category', 'uses' => 'ProductsController@index_category'));
Route::resource('/products', 'ProductsController');

Route::resource('/portfolios', 'PortfoliosController');
Route::get('/portfolios/{id}/box', array('uses' => 'PortfoliosController@show_box'));

Route::post('/upload', array('as' => 'upload', 'uses' => 'UploadController@upload'));

Route::group(array('prefix' => 'admin'), function() {
	Route::resource('/posts', 'admin\PostsController');
	Route::get( '/posts/{id}/translation', array('as' => 'admin..post_translations.set', 'uses' => 'admin\PostTranslationsController@set_translation'));
	Route::post('/posts/{id}/translation', array('as' => 'admin..post_translations.store', 'uses' => 'admin\PostTranslationsController@store'));
	Route::resource('/portfolios', 'admin\PortfoliosController');
	Route::get( '/portfolios/{id}/translation', array('as' => 'admin..portfolio_translations.set', 'uses' => 'admin\PortfolioTranslationsController@set_translation'));
	Route::post('/portfolios/{id}/translation', array('as' => 'admin..portfolio_translations.store', 'uses' => 'admin\PortfolioTranslationsController@store'));
	Route::resource('/pages', 'admin\PagesController');
	Route::get( '/pages/{id}/translation', array('as' => 'admin..page_translations.set', 'uses' => 'admin\PageTranslationsController@set_translation'));
	Route::post('/pages/{id}/translation', array('as' => 'admin..page_translations.store', 'uses' => 'admin\PageTranslationsController@store'));
	Route::resource('/settings', 'admin\SettingsController');
	Route::resource('/categories', 'admin\CategoriesController');
	Route::resource('/products', 'admin\ProductsController');
	Route::resource('/product_categories', 'admin\ProductCategoriesController');
	Route::get( '/products/{id}/translation', array('as' => 'admin..product_translations.set', 'uses' => 'admin\ProductTranslationsController@set_translation'));
	Route::post('/products/{id}/translation', array('as' => 'admin..product_translations.store', 'uses' => 'admin\ProductTranslationsController@store'));
	Route::resource('/users', 'admin\UsersController');
	Route::resource('/menus', 'admin\MenusController');
	Route::post('/menus_update', array('uses' => 'admin\MenusController@updateList'));
	Route::get('sitemap', array('as' => 'admin..sitemap.index', 'uses' => 'admin\SitemapController@index'));
});
Route::get('sitemap.xml', function(){ return Redirect::to('sitemap_index.xml'); });
Route::get('sitemap_index.xml', function(){ return View::make('sitemap_index'); });
Route::get('post-sitemap.xml', array('as' => 'admin..sitemap.index', 'uses' => 'admin\SitemapController@index'));
// Confide routes
Route::get( 'login',                  	   'UserController@login');
Route::get( 'user/login',                  'UserController@login');
Route::post('user/login',                  array( 'as'=>'user..login.do_login', 'uses' => 'UserController@do_login'));
Route::get( 'user/confirm/{code}',         'UserController@confirm');
Route::get( 'user/forgot_password',        'UserController@forgot_password');
Route::post('user/forgot_password',        'UserController@do_forgot_password');
Route::get( 'user/reset_password/{token}', 'UserController@reset_password');
Route::post('user/reset_password',         'UserController@do_reset_password');
Route::get( 'user/logout',                 'UserController@logout');

Route::post('contact', function() {

    $fromEmail = Input::get('email');
    $fromName = Input::get('email');
    $subject = Input::get('subject');
    $data = array( 'message' => Input::get('message') );

    $toEmail = 'waycs16@gmail.com';
    $toName = 'Advance Enpower';

    Mail::send('emails.contact', $data, function($message) use ($toEmail, $toName, $fromEmail, $fromName, $subject)
    {
        $message->to($toEmail, $toName);

        $message->from($fromEmail, $fromName);

        $message->subject($subject);
    });
    
    return Redirect::back();
});

app/views/admin/pages/create.blade.php
@extends('admin.layouts.admin')

@section('main')

<div class="row">
    <div class="col-lg-12">
        <h1>สร้างเพจใหม่</h1>

        @if ($errors->any())
        	<div class="alert alert-danger">
        	    <ul>
                    {{ implode('', $errors->all('<li class="error">:message</li>')) }}
                </ul>
        	</div>
        @endif
    </div>
</div>

{{ Form::open(array('route' => 'admin..pages.store', 'class' => 'form-horizontal', 'id'=> 'my-awesome-dropzone', 'files' => true)) }}

    <div class="form-group">
       
        <div class="col-sm-12">
              {{ Form::text('title', Input::old('title'), array('class'=>'form-control', 'placeholder'=>'Title')) }}
        </div>
    </div>
    <!-- Nav tabs -->
    <ul class="nav nav-tabs">
        <li class="active"><a href="#body" data-toggle="tab">Body</a>
        </li>
        <li><a href="#images" data-toggle="tab">Images</a>
        </li>
        <li><a href="#setting" data-toggle="tab">Setting</a>
        </li>
    </ul>
<!-- Tab panes -->
    <div class="tab-content">
      <div class="tab-pane fade in active" id="body">


        <div class="form-group">
            <div class="col-sm-12">
              {{ Form::textarea('content', Input::old('content'), array('id'=>'editor', 'class'=>'form-control', 'placeholder'=>'Content')) }}
            </div>
        </div>
      </div>

      <div class="tab-pane fade" id="images">

        <div class="form-group">
            {{ Form::label('cover', 'รูปปก:', array('class'=>'col-md-2 control-label')) }}
            <div class="col-sm-12">
              {{ Form::file('cover', Input::old('cover'), array('class'=>'form-control')) }}
            </div>
        </div>
        
        <div class="form-group">
          <label  class="col-md-2 control-label">รูปสไลด์:</label>
          <div id="sortable" class="dropzone dz-clickable dropzone-previews col-md-10">
            
            <div class="dz-default dz-message col-md-9"><span>Drop files here to upload</span></div>
          </div>
          <div class="fallback">
            <input name="images" type="file" multiple />
          </div>
        </div>
      </div>

      <div class="tab-pane fade" id="setting">

        <div class="form-group">
            {{ Form::label('slug', 'Friendly Url:', array('class'=>'col-md-2 control-label')) }}
            <div class="col-sm-10">
              {{ Form::text('slug', Input::old('slug'), array('class'=>'form-control', 'placeholder'=>'Friendly Url')) }}
            </div>
        </div>

        <div class="form-group">
            {{ Form::label('tags', 'Tags:', array('class'=>'col-md-2 control-label')) }}
            <div class="col-sm-10">
              {{ Form::text('tags', Input::old('tags'), array('class'=>'form-control', 'placeholder'=>'Tags', 'data-role'=>"tagsinput")) }}
            </div>
        </div>

        @if(Input::get('page_id'))
        <div class="form-group">
            {{ Form::label('parent_id', 'หน้าหลัก:', array('class'=>'col-md-2 control-label')) }}
            <div class="col-sm-10">
              {{ Form::input('number', 'parent_id', Input::get('page_id'), array('class'=>'form-control')) }}
            </div>
        </div>
        @else
           {{ Form::hidden('parent_id', Input::get('page_id')) }}
        @endif

        <div class="form-group">
            {{ Form::label('style', 'Stylesheet:', array('class'=>'col-md-2 control-label')) }}
            <div class="col-sm-10">
              {{ Form::textarea('style', Input::old('style'), array('id'=>'styleeditor', 'class'=>'form-control', 'placeholder'=>'style')) }}
            </div>
        </div>
      </div>
    </div>
    
  <div class="form-group">
      <label class="col-sm-2 control-label">&nbsp;</label>
      <div class="col-sm-10">
        {{ Form::submit('Create', array('class' => 'btn btn-lg btn-primary', 'data-disable-with'=>"Saving...")) }}
        {{ link_to_route('admin..pages.index', 'Cancel', null, array('class' => 'btn btn-lg btn-default ')) }}
      </div>
  </div>

{{ Form::close() }}

@stop

@section('script')
$(function(){
          $('#editor').editable({
            inlineMode: false, 
            imageUploadURL: '{{ url('/upload') }}',
            imageParams: {id: "my_editor"},    
            buttons: ["bold", "italic", "underline", "strikeThrough", "fontSize", "color", "formatBlock", "align", "insertOrderedList", "insertUnorderedList", "outdent", "indent", "selectAll", "createLink", "anchor", "insertImage", "insertVideo", "undo", "redo", "html"], 
            blockTags: ['p'], 
            customButtons: {
            anchor: {
              title: 'Anchor',
              icon: {
                type: 'font',
                value: 'fa fa-anchor'
              },
              callback: function (editor){
                var anchor_id = prompt("Set anchor id");
                editor.insertHTML("<a id='" + anchor_id + "' class='fa-anchor f-link f-anchor'></a>");
              }
            }
          }
          })
      });
Dropzone.autoDiscover = false;
$(document).ready(function(){
Dropzone.options.myAwesomeDropzone = { // The camelized version of the ID of the form element

  // The configuration we've talked about above
  autoProcessQueue: false,
  uploadMultiple: true,
  parallelUploads: 10,
  maxFiles: 10,
  paramName: "images",
  previewsContainer: ".dropzone-previews",
  addRemoveLinks: true,
  clickable: '.dropzone-previews',
  removedfile: function(file) {
    var _ref;
    return (_ref = file.previewElement) != null ? _ref.parentNode.removeChild(file.previewElement) : void 0;
  },
  // The setting up of the dropzone
  init: function() {
    var myDropzone = this;

    // First change the button to actually tell Dropzone to process the queue.
    this.element.querySelector("input[type=submit]").addEventListener("click", function(e) {
      // Make sure that the form isn't actually being sent.
      e.preventDefault();
      e.stopPropagation();
      if(myDropzone.files.length > 0)
      {
        myDropzone.processQueue();
      }
      else
      {
        $( "#my-awesome-dropzone" ).submit();  
      } 
    });

    // Listen to the sendingmultiple event. In this case, it's the sendingmultiple event instead
    // of the sending event because uploadMultiple is set to true.
    this.on("sendingmultiple", function(file, xhr, formData) {
      formData.append('cover', $('#cover')[0].files[0]);
      $('#cover').remove();
      $("input[type=submit]").prop('disabled', true);
    });
    this.on("successmultiple", function(files, response) {
      location = '{{{ action('admin\PagesController@index') }}}';
    });
    this.on("errormultiple", function(files, response) {
      // Gets triggered when there was an error sending the files.
      // Maybe show form again, and notify user of error
      $("input[type=submit]").prop('disabled', false);
    });
  }

}

var myDropzone = new Dropzone("form#my-awesome-dropzone", Dropzone.options.myAwesomeDropzone);
myDropzone.on("addedfile", function(file) {
  var file_id = file.name;
  if(!$.isNumeric(file_id))
  {
    file_id = ($('.image_caption').length + 1) * 100;
  }

  var captionInput = Dropzone.createElement("<textarea class='images_update_" + file_id + "_caption image_caption' name='images_update[" + file.name + "][caption]' maxlength='250' placeholder='Enter a caption' ></textarea>");
  file.previewElement.appendChild(captionInput);
  file.previewElement.addEventListener("click", function() { myDropzone.removeFile(file); });

  $('textarea.images_update_' + file_id + '_caption').click(function(e){
    e.stopPropagation();
  });
});
$( "#sortable" ).sortable();

});

@stop

app/views/admin/pages/edit.blade.php
@extends('admin.layouts.admin')

@section('main')

<div class="row">
    <div class="col-lg-12">
        <h1>แก้ไขเพจ <span><a href="{{ url(action('admin\PageTranslationsController@set_translation', $page->id)) }}">{{ HTML::image(url('/assets/images/en-flag.png'), 'Set English translation', array('style' => 'height:30px; width:auto;')) }}</a></span></h1>

        @if ($errors->any())
        	<div class="alert alert-danger">
        	    <ul>
                    {{ implode('', $errors->all('<li class="error">:message</li>')) }}
                </ul>
        	</div>
        @endif
    </div>
</div>

{{ Form::model($page, array('class' => 'form-horizontal', 'id'=> 'my-awesome-dropzone', 'method' => 'PATCH', 'route' => array('admin..pages.update', $page->id), 'files' => true)) }}

    <div class="form-group">
       
        <div class="col-sm-12">
              {{ Form::text('title', Input::old('title'), array('class'=>'form-control', 'placeholder'=>'Title')) }}
        </div>
    </div>
    <!-- Nav tabs -->
    <ul class="nav nav-tabs">
        <li class="active"><a href="#body" data-toggle="tab">Body</a>
        </li>
        <li><a href="#images" data-toggle="tab">Images</a>
        </li>
        <li><a href="#setting" data-toggle="tab">Setting</a>
        </li>
    </ul>
<!-- Tab panes -->
    <div class="tab-content">
      <div class="tab-pane fade in active" id="body">


        <div class="form-group">
            {{ Form::textarea('content', Input::old('content'), array('id'=>'editor', 'class'=>'form-control', 'placeholder'=>'Content')) }}
        </div>
      </div>

      <div class="tab-pane fade" id="images">

        <div class="form-group">
            {{ Form::label('cover', 'รูปปก:', array('class'=>'col-md-2 control-label')) }}
            <div class="col-sm-10">
              {{ HTML::image($page->cover->url('thumb'), "Cover") }}
              {{ Form::file('cover', Input::old('cover'), array('class'=>'form-control')) }}
            </div>
        </div>
        
        <div class="form-group">
          <label  class="col-md-2 control-label">รูปสไลด์:</label>
          <div id="sortable" class="dropzone dz-clickable dropzone-previews col-md-10">
            
            <div class="dz-default dz-message col-md-9"><span>Drop files here to upload</span></div>
          </div>
          <div class="fallback">
            <input name="images" type="file" multiple />
          </div>
        </div>
      </div>

      <div class="tab-pane fade" id="setting">

        <div class="form-group">
            {{ Form::label('slug', 'Friendly Url:', array('class'=>'col-md-2 control-label')) }}
            <div class="col-sm-10">
              {{ Form::text('slug', Input::old('slug'), array('class'=>'form-control', 'placeholder'=>'Friendly Url')) }}
            </div>
        </div>

        <div class="form-group">
            {{ Form::label('tags', 'Tags:', array('class'=>'col-md-2 control-label')) }}
            <div class="col-sm-10">
              {{ Form::text('tags', Input::old('tags'), array('class'=>'form-control', 'placeholder'=>'Tags', 'data-role'=>"tagsinput")) }}
            </div>
        </div>

        @if(Input::get('page_id'))
        <div class="form-group">
            {{ Form::label('parent_id', 'หน้าหลัก:', array('class'=>'col-md-2 control-label')) }}
            <div class="col-sm-10">
              {{ Form::input('number', 'parent_id', Input::get('page_id'), array('class'=>'form-control')) }}
            </div>
        </div>
        @else
           <?php $parent_page = Page::lists('title', 'id'); 
              $parent_page = [ '0' => 'ไม่มีหน้าหลัก'] + $parent_page;
              $has_parent = Input::old('parent_id') ? Input::old('parent_id') : Input::get('parent_id');
            ?>
            <div class="form-group">
                  {{ Form::label('parent_id', 'หน้าหลัก:', array('class'=>'col-md-2 control-label')) }}
                <div class="col-sm-4">
                  {{ Form::select('parent_id', $parent_page, $has_parent, array('class'=>'form-control', 'placeholder'=>'หน้าหลัก')) }}
                </div>
            </div>
        @endif

        <div class="form-group">
            {{ Form::label('style', 'Stylesheet:', array('class'=>'col-md-2 control-label')) }}
            <div class="col-sm-10">
              {{ Form::textarea('style', Input::old('style'), array('id'=>'styleeditor', 'class'=>'form-control', 'placeholder'=>'style')) }}
            </div>
        </div>
      </div>
    </div>

<div class="form-group">
    <label class="col-sm-2 control-label">&nbsp;</label>
    <div class="col-sm-10">
      {{ Form::submit('Update', array('class' => 'btn btn-lg btn-primary', 'data-disable-with'=>"Updating...")) }}
      {{ link_to_route('admin..pages.index', 'Cancel', $page->id, array('class' => 'btn btn-lg btn-default')) }}
    </div>
</div>

{{ Form::close() }}

@stop

@section('script')
$(function(){
$('#editor').editable({
            inlineMode: false, 
            imageUploadURL: '{{ url('/upload') }}',
            imageParams: {id: "my_editor"},    
            buttons: ["bold", "italic", "underline", "strikeThrough", "fontSize", "color", "formatBlock", "align", "insertOrderedList", "insertUnorderedList", "outdent", "indent", "selectAll", "createLink", "anchor", "insertImage", "insertVideo", "undo", "redo", "html"], 
            blockTags: ['p'], 
            customButtons: {
            anchor: {
              title: 'Anchor',
              icon: {
                type: 'font',
                value: 'fa fa-anchor'
              },
              callback: function (editor){
                var anchor_id = prompt("Set anchor id");
                editor.insertHTML("<a id='" + anchor_id + "' class='fa-anchor f-link f-anchor'></a>");
              }
            }
          }
          })
});
Dropzone.autoDiscover = false;
$(document).ready(function(){
Dropzone.options.myAwesomeDropzone = { // The camelized version of the ID of the form element

  // The configuration we've talked about above
  autoProcessQueue: false,
  uploadMultiple: true,
  parallelUploads: 10,
  maxFiles: 10,
  paramName: "images",
  previewsContainer: ".dropzone-previews",
  addRemoveLinks: true,
  clickable: '.dropzone-previews',
  removedfile: function(file) {
    var _ref;
    var file_id = file.name;
    $('<input>').attr({
      type: 'hidden',
      id: 'file_to_delete_' + file_id,
      name: 'deleted_files[]',
      value: file_id
  }).appendTo('form');
    return (_ref = file.previewElement) != null ? _ref.parentNode.removeChild(file.previewElement) : void 0;
  },
  // The setting up of the dropzone
  init: function() {
    var myDropzone = this;

    // First change the button to actually tell Dropzone to process the queue.
    this.element.querySelector("input[type=submit]").addEventListener("click", function(e) {
      // Make sure that the form isn't actually being sent.
      e.preventDefault();
      e.stopPropagation();
      if(myDropzone.files.length > 0)
      {
        myDropzone.processQueue();
      }
      else
      {
        $( "#my-awesome-dropzone" ).submit();  
      } 
    });

    // Listen to the sendingmultiple event. In this case, it's the sendingmultiple event instead
    // of the sending event because uploadMultiple is set to true.
    this.on("sendingmultiple", function(file, xhr, formData) {
      if($('#cover')[0].files[0])
      {
        formData.append('cover', $('#cover')[0].files[0]);
        $('#cover').remove();
      }
      $("input[type=submit]").remove();
    });
    this.on("successmultiple", function(files, response) {
      location = '{{{ action('admin\PagesController@index') }}}';
    });
    this.on("errormultiple", function(files, response) {
      $("input[type=submit]").prop('disabled', false);
    });
  }

}

var myDropzone = new Dropzone("form#my-awesome-dropzone", Dropzone.options.myAwesomeDropzone);
myDropzone.on("addedfile", function(file) {
  var file_id = file.name;
  if(!$.isNumeric(file_id))
  {
    file_id = ($('.image_caption').length + 1) * 100;
  }

  var captionInput = Dropzone.createElement("<textarea class='images_update_" + file_id + "_caption image_caption' name='images_update[" + file.name + "][caption]' maxlength='250' placeholder='Enter a caption' ></textarea>");
  file.previewElement.appendChild(captionInput);
  file.previewElement.addEventListener("click", function() { myDropzone.removeFile(file); });

  $('textarea.images_update_' + file_id + '_caption').click(function(e){
    e.stopPropagation();
  });
});

var uploadedFile = {};

@foreach ($page->images as $image)
  uploadedFile = { name: "{{{ $image->id }}}", size: "{{{ $image->image_file_size }}}"};
  myDropzone.emit("addedfile", uploadedFile);
  myDropzone.emit("thumbnail", uploadedFile, "{{{ $image->image->url('thumb') }}}");  
  $('textarea.images_update_{{ $image->id }}_caption').val("{{ $image->caption }}");
@endforeach

myDropzone.options.maxFiles = myDropzone.options.maxFiles - {{{ $page->images->count() }}};

$( "#sortable" ).sortable();

});

@stop

app/views/admin/pages/index.blade.php
@extends('admin.layouts.admin')

@section('main')

<div class="row">
	<div class="col-lg-12">
		<h1>เพจทั้งหมด</h1>

        @if ($errors->any())
        	<div class="alert alert-danger">
        	    <ul>
                    {{ implode('', $errors->all('<li class="error">:message</li>')) }}
                </ul>
        	</div>
        @endif
    </div>

</div>
<div  class="tree well">
	<ul>
		<li><span><i class="fa fa-home fa-fw"></i>Root</span>
		<ul id="sortable">
@if ($pages->count())
			@foreach ($pages as $page)
				
			<li>
				<span><i class="fa fa-tablet fa-fw"></i>{{{ $page->title }}}</span>
				<span>{{ Form::open(array('style' => 'display: inline-block;', 'method' => 'DELETE', 'route' => array('admin..pages.destroy', $page->id))) }}
                        {{ Form::submit('Delete', array('class' => 'btn btn-danger btn-xs', 'data-confirm' => 'Are you sure?')) }}
                    {{ Form::close() }}
                    {{ link_to_route('admin..pages.edit', 'Edit', array($page->id), array('class' => 'btn btn-info btn-xs')) }}
                    {{ link_to_route('pages.show', 'View', array($page->slug), array('class' => 'btn btn-success btn-xs', 'target' => '_blank')) }}
          		</span>
          		<span>{{ link_to_route('admin..pages.create', 'เพิ่ม subpage', array('page_id' => $page->id), array('class' => 'btn btn-primary btn-xs')) }}</span>
				<span><a href="{{ url(action('admin\PageTranslationsController@set_translation', $page->id)) }}">{{ HTML::image(url('/assets/images/en-flag.png'), 'Set English translation', array('style' => 'height:22px; width:auto;')) }}</a></span>
          		<?php $subpages = Page::where('parent_id', $page->id)->get(); ?>
          		@if($subpages->count() > 0 )
          			<ul id="sortable">
          			@foreach ($subpages as $subpage)
          				<li>
          				<span><i class="fa fa-tablet fa-fw"></i>{{{ $subpage->title }}}</span>
										<span>{{ Form::open(array('style' => 'display: inline-block;', 'method' => 'DELETE', 'route' => array('admin..pages.destroy', $subpage->id))) }}
		                        {{ Form::submit('Delete', array('class' => 'btn btn-danger btn-xs', 'data-confirm' => 'Are you sure?')) }}
		                    {{ Form::close() }}
		                    {{ link_to_route('admin..pages.edit', 'Edit', array($subpage->id), array('class' => 'btn btn-info btn-xs')) }}

                        {{ link_to_route('pages.show', 'View', array($subpage->slug), array('class' => 'btn btn-success btn-xs', 'target' => '_blank')) }}
		          		</span>
		          		<span>{{ link_to_route('admin..pages.create', 'เพิ่ม subpage', array('page_id' => $subpage->id), array('class' => 'btn btn-primary btn-xs')) }}</span>
						<span><a href="{{ url(action('admin\PageTranslationsController@set_translation', $subpage->id)) }}">{{ HTML::image(url('/assets/images/en-flag.png'), 'Set English translation', array('style' => 'height:22px; width:auto;')) }}</a></span>
		          		<?php $lv3_subpages = Page::where('parent_id', $subpage->id)->get(); ?>
		          		@if($lv3_subpages->count() > 0 )
		          			<ul id="sortable">
		          			@foreach ($lv3_subpages as $lv_subpage)
		          				<li>
		          				<span><i class="fa fa-tablet fa-fw"></i>{{{ $lv_subpage->title }}}</span>
												<span>{{ Form::open(array('style' => 'display: inline-block;', 'method' => 'DELETE', 'route' => array('admin..pages.destroy', $lv_subpage->id))) }}
				                        {{ Form::submit('Delete', array('class' => 'btn btn-danger btn-xs', 'data-confirm' => 'Are you sure?')) }}
				                    {{ Form::close() }}
				                    {{ link_to_route('admin..pages.edit', 'Edit', array($lv_subpage->id), array('class' => 'btn btn-info btn-xs')) }}

		                        {{ link_to_route('pages.show', 'View', array($lv_subpage->slug), array('class' => 'btn btn-success btn-xs', 'target' => '_blank')) }}
				          		</span>
		          				</li>
							@endforeach		
		          			</ul>
		          		@endif
          				</li>
					@endforeach		
          			</ul>
          		@endif
			</li>
			@endforeach	
@else
			<li>
				<span>ยังไม่มีเพจ</span>
			</li>
@endif	
			<li>
				<span>{{ link_to_route('admin..pages.create', 'สร้างเพจใหม่', null, array('class' => 'btn btn-xs btn-success pull-right')) }}	
         		</span>
			</li>
		</ul>
		</li>
	</ul>
</div>
@stop